### ISSUE TITLE
Kubernator terminated with an error: Got an unexpected keyword argument 'field_validation' to method patch_namespaced_custom_object

### ISSUE THREAD

**Issue by arcivanov** [karellen/kubernator#40]
```
2023-12-27T01:04:25.412048 kubernator CRITICAL app.py:489 Kubernator terminated with an error: Got an unexpected keyword argument 'field_validation' to method patch_namespaced_custom_object
Traceback (most recent call last):
  File "/home/arcivanov/.local/lib/python3.11/site-packages/kubernator/app.py", line 485, in main
    app.run()
  File "/home/arcivanov/.local/lib/python3.11/site-packages/kubernator/app.py", line 199, in run
    self._run_handlers(KubernatorPlugin.handle_apply, True, context, None)
  File "/home/arcivanov/.local/lib/python3.11/site-packages/kubernator/app.py", line 277, in _run_handlers
    self._set_plugin_context(__reverse, __context, run)
  File "/home/arcivanov/.local/lib/python3.11/site-packages/kubernator/app.py", line 282, in _set_plugin_context
    run(h)
  File "/home/arcivanov/.local/lib/python3.11/site-packages/kubernator/app.py", line 271, in run
    h_f(*args, **kwargs)
  File "/home/arcivanov/.local/lib/python3.11/site-packages/kubernator/plugins/k8s.py", line 280, in handle_apply
    self._apply_resource(dry_run,
  File "/home/arcivanov/.local/lib/python3.11/site-packages/kubernator/plugins/k8s.py", line 424, in _apply_resource
    merged_resource = resource.patch(resource.manifest,
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/arcivanov/.local/lib/python3.11/site-packages/kubernator/plugins/k8s_api.py", line 457, in patch
    resp = rdef.patch(**kwargs)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/arcivanov/.local/lib/python3.11/site-packages/kubernetes/client/api/custom_objects_api.py", line 2941, in patch_namespaced_custom_object
    return self.patch_namespaced_custom_object_with_http_info(group, version, namespace, plural, name, body, **kwargs)  # noqa: E501
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/arcivanov/.local/lib/python3.11/site-packages/kubernetes/client/api/custom_objects_api.py", line 3000, in patch_namespaced_custom_object_with_http_info
    raise ApiTypeError(
kubernetes.client.exceptions.ApiTypeError: Got an unexpected keyword argument 'field_validation' to method patch_namespaced_custom_object
```

**Comment by arcivanov** [comment]
This is a bug in K8S Python Client: https://github.com/kubernetes-client/python/issues/2171

**Comment by arcivanov** [comment]
Attempting to fix this here: https://github.com/kubernetes-client/gen/issues/259
